// 3.5 PHB/SRD combat actions. Entries needing targets or an adjudication remain explicit reminders.
export const COMMON_ACTIONS = [
  { id: "step", name: "五尺快步", kind: "free", text: "本回合改用五尺安全移动。" },
  { id: "move", name: "移动", kind: "move", text: "移动不超过当前速度；距离另由地图记录。" },
  { id: "double-move", name: "双重移动", kind: "full", text: "使用标准和移动动作进行两次移动。" },
  { id: "charge", name: "冲锋", kind: "full", text: "进入原生攻击窗口，勾选冲锋；路径与距离按实际场景核对。" },
  { id: "withdraw", name: "撤退", kind: "full", text: "撤退通常移动至两倍速度；只有起始格免除相应移动借机，后续威胁格仍需检查。" },
  { id: "run", name: "奔跑", kind: "full", text: "通常四倍速度；重甲或重载通常三倍。直线路径及敏捷防御损失需核对。" },
  { id: "defense", name: "全防御", kind: "standard", text: "使用全防御，AC获得+4闪避加值；翻滚至少5级时为+6。" },
  { id: "defensive", name: "防御式战斗", kind: "standard", text: "进入原生攻击窗口，勾选防御式战斗。" },
  { id: "aid", name: "援助他人", kind: "standard", text: "按本次援助对象进行攻击或技能检定，成功后由DM核对对应加值。" },
  { id: "feint", name: "虚招", kind: "standard", text: "以唬骗对抗察言观色；成功后对方在你的下次近战攻击中失去敏捷防御。精通虚招等能力可改变动作成本，由DM核对。" },
  { id: "grapple", name: "擒抱", kind: "standard", text: "通常以一次近战攻击尝试抓握并进行擒抱检定；借机、体型和后续对抗在原生角色卡中结算。全攻击中替换攻击时手动更正动作提醒。" },
  { id: "escape-grapple", name: "挣脱擒抱", kind: "standard", text: "以擒抱检定对抗记录的擒抱对手；脱逃术的整轮挣脱可从状态详情使用。" },
  { id: "first-aid", name: "急救", kind: "standard", text: "对指定的濒死目标进行DC15医疗检定，成功使伤势稳定。" },
  { id: "wake-fascinated", name: "唤醒迷魂者", kind: "standard", text: "用一个标准动作将相邻的迷魂者唤醒。" },
  { id: "trip", name: "绊摔", kind: "standard", text: "通常替换一次近战攻击，先接触攻击再进行对抗；精通绊摔等例外由DM确认。全攻击中的一次绊摔不另占标准动作，请更正提醒。" },
  { id: "disarm", name: "卸除武器", kind: "standard", text: "通常替换一次近战攻击，双方对抗攻击检定；借机与精通卸除武器等例外由DM确认。全攻击时更正动作提醒。" },
  { id: "sunder", name: "击破武器", kind: "standard", text: "通常替换一次攻击，对抗成功后结算物品硬度与HP；物品伤害不自动扣除。全攻击时更正动作提醒。" },
  { id: "bull-rush", name: "冲撞", kind: "standard", text: "通常标准动作，也可在冲锋中尝试；双方力量对抗、移动与借机由DM结算。" },
  { id: "overrun", name: "闯越", kind: "standard", text: "标准动作并发生在移动期间；避让、对抗与借机由DM核对，移动距离仍计入实际路径。" },
  { id: "coup", name: "致命一击", kind: "full", text: "贴近无助目标，自动命中并造成重击；结算伤害与强韧免死豁免。此动作引发借机攻击。" },
  { id: "reload", name: "装填", kind: "move", text: "轻弩或手弩通常为移动动作；重弩通常为全回合动作，快速装填等能力可改变成本，按实际武器更正提醒。" },
  { id: "mount", name: "上／下坐骑", kind: "move", text: "通常移动动作；快速上马／下马可通过骑术检定成为自由动作，请按实际结果更正提醒。" },
  { id: "ready", name: "准备动作", kind: "standard", text: "声明触发条件及准备的标准、移动或自由动作。" },
  { id: "delay", name: "延迟行动", kind: null, text: "延后自己的先攻；不是自由动作，不扣动作提醒，由DM调整先攻顺序。" },
  { id: "draw", name: "拔出／收起武器", kind: "move", text: "通常移动动作；快速拔刀或与移动结合时按相应能力处理。" },
  { id: "stand", name: "起身", kind: "move", text: "从俯卧起身，通常引发借机攻击。" },
  { id: "pick", name: "拾取物品", kind: "move", text: "拾取地面物品，通常引发借机攻击。" },
  { id: "door", name: "开／关门", kind: "move", text: "通常移动动作，物体交互由玩家在场景执行。" },
  { id: "drop", name: "丢弃物品", kind: "free", text: "通常自由动作；数量及物品位置由玩家确认。" },
  { id: "prone", name: "卧倒", kind: "free", text: "使角色进入俯卧状态。" },
  { id: "speak", name: "说话", kind: "free", text: "简短交谈通常自由动作。" },
  { id: "aao", name: "借机攻击", kind: "immediate", text: "使用原生近战攻击，HUD记录到反应动作；由DM确认触发时机。" },
  { id: "movement-correction", name: "更正移动", kind: null, text: "清空移动记录；战斗中由DM更正，战斗外可自行清空。" }
];
